name: Build and Deploy Eleventy Site

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Match your project's Node version

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build  # Uses the "build" script from package.json

      - name: Setup SSH Key & Trust Host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_edtorr
          chmod 600 ~/.ssh/id_rsa_edtorr
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy via Rsync
        run: |
            rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa_edtorr -o StrictHostKeyChecking=no" ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/public_html/
        